// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: 2021-11-26T09:27:01Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/cg917658910/fzkj-wallet/quote-service/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC QuoteServiceServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.QuoteServiceServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// quoteservice

		healthcheck: grpctransport.NewServer(
			endpoints.HealthCheckEndpoint,
			DecodeGRPCHealthCheckRequest,
			EncodeGRPCHealthCheckResponse,
			serverOptions...,
		),
		fiatquote: grpctransport.NewServer(
			endpoints.FiatQuoteEndpoint,
			DecodeGRPCFiatQuoteRequest,
			EncodeGRPCFiatQuoteResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the QuoteServiceServer interface
type grpcServer struct {
	healthcheck grpctransport.Handler
	fiatquote   grpctransport.Handler
}

// Methods for grpcServer to implement QuoteServiceServer interface

func (s *grpcServer) HealthCheck(ctx context.Context, req *pb.HealthCheckRequest) (*pb.HealthCheckResponse, error) {
	_, rep, err := s.healthcheck.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.HealthCheckResponse), nil
}

func (s *grpcServer) FiatQuote(ctx context.Context, req *pb.FiatQuoteRequest) (*pb.FiatQuoteResponse, error) {
	_, rep, err := s.fiatquote.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.FiatQuoteResponse), nil
}

// Server Decode

// DecodeGRPCHealthCheckRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC healthcheck request to a user-domain healthcheck request. Primarily useful in a server.
func DecodeGRPCHealthCheckRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.HealthCheckRequest)
	return req, nil
}

// DecodeGRPCFiatQuoteRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC fiatquote request to a user-domain fiatquote request. Primarily useful in a server.
func DecodeGRPCFiatQuoteRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.FiatQuoteRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCHealthCheckResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain healthcheck response to a gRPC healthcheck reply. Primarily useful in a server.
func EncodeGRPCHealthCheckResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.HealthCheckResponse)
	return resp, nil
}

// EncodeGRPCFiatQuoteResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain fiatquote response to a gRPC fiatquote reply. Primarily useful in a server.
func EncodeGRPCFiatQuoteResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.FiatQuoteResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
