#config.yaml
MySQL: # MySQL配置
  host: 127.0.0.1
  port: 3306
  user: root
  password: cg123456 
  db_name: huadong
Kafka: # Kafka配置
  brokers: localhost:9092
  order_notify_topic: wallet.topic.test.order.notify
  order_notify_result_topics: test.topic.order.notify.result,cg.topic.order.notify.result
  order_notify_result_default_topic: default.topic.test.order.notify.result
  order_notify_consumer_group: cg.group.test.order.notify
OrderNotify: # Order Notify
  order_notify_caller_worker_num: 1000
  order_notify_retry_num: 3
  order_notify_retry_delay_time_s: 3
Redis: #redis
  url: 
  order_notify_result_prefix: Cg:Notify:Order:Result