run:
	go run ./cmd/cli/main.go
truss:
	truss proto/notifysvc.proto  --pbpkg github.com/cg917658910/fzkj-wallet/notify-service/proto --svcpkg github.com/cg917658910/fzkj-wallet/notify-service --svcout . -v 
