// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: 2021-11-26T09:27:01Z

// Package grpc provides a gRPC client for the NotifyService service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/cg917658910/fzkj-wallet/notify-service/proto"
	"github.com/cg917658910/fzkj-wallet/notify-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.NotifyServiceServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var healthcheckEndpoint endpoint.Endpoint
	{
		healthcheckEndpoint = grpctransport.NewClient(
			conn,
			"notifysvc.NotifyService",
			"HealthCheck",
			EncodeGRPCHealthCheckRequest,
			DecodeGRPCHealthCheckResponse,
			pb.HealthCheckResponse{},
			clientOptions...,
		).Endpoint()
	}

	var ordernotifystartEndpoint endpoint.Endpoint
	{
		ordernotifystartEndpoint = grpctransport.NewClient(
			conn,
			"notifysvc.NotifyService",
			"OrderNotifyStart",
			EncodeGRPCOrderNotifyStartRequest,
			DecodeGRPCOrderNotifyStartResponse,
			pb.OrderNotifyStartResponse{},
			clientOptions...,
		).Endpoint()
	}

	var ordernotifystopEndpoint endpoint.Endpoint
	{
		ordernotifystopEndpoint = grpctransport.NewClient(
			conn,
			"notifysvc.NotifyService",
			"OrderNotifyStop",
			EncodeGRPCOrderNotifyStopRequest,
			DecodeGRPCOrderNotifyStopResponse,
			pb.OrderNotifyStopResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		HealthCheckEndpoint:      healthcheckEndpoint,
		OrderNotifyStartEndpoint: ordernotifystartEndpoint,
		OrderNotifyStopEndpoint:  ordernotifystopEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCHealthCheckResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC healthcheck reply to a user-domain healthcheck response. Primarily useful in a client.
func DecodeGRPCHealthCheckResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.HealthCheckResponse)
	return reply, nil
}

// DecodeGRPCOrderNotifyStartResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC ordernotifystart reply to a user-domain ordernotifystart response. Primarily useful in a client.
func DecodeGRPCOrderNotifyStartResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.OrderNotifyStartResponse)
	return reply, nil
}

// DecodeGRPCOrderNotifyStopResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC ordernotifystop reply to a user-domain ordernotifystop response. Primarily useful in a client.
func DecodeGRPCOrderNotifyStopResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.OrderNotifyStopResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCHealthCheckRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain healthcheck request to a gRPC healthcheck request. Primarily useful in a client.
func EncodeGRPCHealthCheckRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.HealthCheckRequest)
	return req, nil
}

// EncodeGRPCOrderNotifyStartRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain ordernotifystart request to a gRPC ordernotifystart request. Primarily useful in a client.
func EncodeGRPCOrderNotifyStartRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.OrderNotifyStartRequest)
	return req, nil
}

// EncodeGRPCOrderNotifyStopRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain ordernotifystop request to a gRPC ordernotifystop request. Primarily useful in a client.
func EncodeGRPCOrderNotifyStopRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.OrderNotifyStopRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
