// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 5f7d5bf015
// Version Date: 2021-11-26T09:27:01Z

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/cg917658910/fzkj-wallet/notify-service/proto"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC NotifyServiceServer.
func MakeGRPCServer(endpoints Endpoints, options ...grpctransport.ServerOption) pb.NotifyServiceServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	serverOptions = append(serverOptions, options...)
	return &grpcServer{
		// notifyservice

		healthcheck: grpctransport.NewServer(
			endpoints.HealthCheckEndpoint,
			DecodeGRPCHealthCheckRequest,
			EncodeGRPCHealthCheckResponse,
			serverOptions...,
		),
		ordernotifystart: grpctransport.NewServer(
			endpoints.OrderNotifyStartEndpoint,
			DecodeGRPCOrderNotifyStartRequest,
			EncodeGRPCOrderNotifyStartResponse,
			serverOptions...,
		),
		ordernotifystop: grpctransport.NewServer(
			endpoints.OrderNotifyStopEndpoint,
			DecodeGRPCOrderNotifyStopRequest,
			EncodeGRPCOrderNotifyStopResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the NotifyServiceServer interface
type grpcServer struct {
	healthcheck      grpctransport.Handler
	ordernotifystart grpctransport.Handler
	ordernotifystop  grpctransport.Handler
}

// Methods for grpcServer to implement NotifyServiceServer interface

func (s *grpcServer) HealthCheck(ctx context.Context, req *pb.HealthCheckRequest) (*pb.HealthCheckResponse, error) {
	_, rep, err := s.healthcheck.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.HealthCheckResponse), nil
}

func (s *grpcServer) OrderNotifyStart(ctx context.Context, req *pb.OrderNotifyStartRequest) (*pb.OrderNotifyStartResponse, error) {
	_, rep, err := s.ordernotifystart.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.OrderNotifyStartResponse), nil
}

func (s *grpcServer) OrderNotifyStop(ctx context.Context, req *pb.OrderNotifyStopRequest) (*pb.OrderNotifyStopResponse, error) {
	_, rep, err := s.ordernotifystop.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.OrderNotifyStopResponse), nil
}

// Server Decode

// DecodeGRPCHealthCheckRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC healthcheck request to a user-domain healthcheck request. Primarily useful in a server.
func DecodeGRPCHealthCheckRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.HealthCheckRequest)
	return req, nil
}

// DecodeGRPCOrderNotifyStartRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC ordernotifystart request to a user-domain ordernotifystart request. Primarily useful in a server.
func DecodeGRPCOrderNotifyStartRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.OrderNotifyStartRequest)
	return req, nil
}

// DecodeGRPCOrderNotifyStopRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC ordernotifystop request to a user-domain ordernotifystop request. Primarily useful in a server.
func DecodeGRPCOrderNotifyStopRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.OrderNotifyStopRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCHealthCheckResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain healthcheck response to a gRPC healthcheck reply. Primarily useful in a server.
func EncodeGRPCHealthCheckResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.HealthCheckResponse)
	return resp, nil
}

// EncodeGRPCOrderNotifyStartResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain ordernotifystart response to a gRPC ordernotifystart reply. Primarily useful in a server.
func EncodeGRPCOrderNotifyStartResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.OrderNotifyStartResponse)
	return resp, nil
}

// EncodeGRPCOrderNotifyStopResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain ordernotifystop response to a gRPC ordernotifystop reply. Primarily useful in a server.
func EncodeGRPCOrderNotifyStopResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.OrderNotifyStopResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
